2021-02-08 13:46:28,440 INFO    MainThread:14984 [wandb_setup.py:_flush():70] setting env: {}
2021-02-08 13:46:28,440 INFO    MainThread:14984 [wandb_setup.py:_flush():70] multiprocessing start_methods=spawn
2021-02-08 13:46:28,440 INFO    MainThread:14984 [wandb_setup.py:_flush():70] setting login settings: {}
2021-02-08 13:46:28,440 INFO    MainThread:14984 [wandb_init.py:_log_setup():318] Logging user logs to C:\Users\lucki\WORK\OFFICE\VAST\Invoice\yolov5-master\wandb\run-20210208_134628-12qsx6eb\logs\debug.log
2021-02-08 13:46:28,440 INFO    MainThread:14984 [wandb_init.py:_log_setup():319] Logging internal logs to C:\Users\lucki\WORK\OFFICE\VAST\Invoice\yolov5-master\wandb\run-20210208_134628-12qsx6eb\logs\debug-internal.log
2021-02-08 13:46:31,400 INFO    MainThread:14984 [wandb_run.py:_console_start():1399] atexit reg
2021-02-08 13:46:31,401 INFO    MainThread:14984 [wandb_run.py:_redirect():1262] redirect: SettingsConsole.WRAP
2021-02-08 13:46:31,401 INFO    MainThread:14984 [wandb_run.py:_redirect():1297] Wrapping output streams.
2021-02-08 13:46:31,401 INFO    MainThread:14984 [wandb_run.py:_redirect():1313] Redirects installed.
2021-02-08 13:46:52,827 INFO    MainThread:14984 [wandb_run.py:_atexit_cleanup():1369] got exitcode: 1
2021-02-08 13:46:52,833 INFO    MainThread:14984 [wandb_run.py:_restore():1341] restore
2021-02-08 13:46:53,194 INFO    MainThread:14984 [wandb_run.py:_wait_for_finish():1492] got exit ret: file_counts {
  wandb_count: 1
  media_count: 2
}
pusher_stats {
  uploaded_bytes: 788
  total_bytes: 481839
}

2021-02-08 13:46:55,211 INFO    MainThread:14984 [wandb_run.py:_wait_for_finish():1492] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
  media_count: 2
}
pusher_stats {
  uploaded_bytes: 493788
  total_bytes: 493788
}

2021-02-08 13:46:56,306 INFO    MainThread:14984 [wandb_run.py:_show_summary():1647] rendering summary
2021-02-08 13:46:56,307 INFO    MainThread:14984 [wandb_run.py:_show_history():1685] rendering history
2021-02-08 13:46:56,308 INFO    MainThread:14984 [wandb_run.py:_show_files():1714] logging synced files
2021-02-08 13:46:56,310 INFO    MainThread:14984 [internal.py:handle_exit():156] Internal process exited
